var m = {
  "_assign": null,
  "_comments": null,
  "_liked_by": null,
  "_user_tags": null,
  "amended_from": "00015/2024",
  "apply_tax_withholding_amount": 0,
  "auto_repeat": null,
  "bank": null,
  "bank_account": null,
  "bank_account_no": null,
  "base_paid_amount": 100000,
  "base_paid_amount_after_tax": 100000,
  "base_received_amount": 100000,
  "base_received_amount_after_tax": 100000,
  "base_total_allocated_amount": 100000,
  "base_total_taxes_and_charges": 0,
  "clearance_date": null,
  "company": "Saadi",
  "contact_email": null,
  "contact_person": null,
  "cost_center": null,
  "creation": "2024-10-24 13:53:28.991239",
  "custom_amount_due": 0,
  "custom_observation": null,
  "custom_party_sold": 0,
  "custom_pay_remaining": 830160,
  "custom_remarks": 0,
  "custom_total_unpaid": 0,
  "difference_amount": 0,
  "docstatus": 1,
  "idx": 0,
  "letter_head": "En-Tête",
  "mode_of_payment": null,
  "modified": "2024-10-24 13:53:39.218619",
  "modified_by": "Administrator",
  "name": "00015/2024-1",
  "naming_series": "ACC-PAY-.YYYY.-",
  "owner": "Administrator",
  "paid_amount": 100000,
  "paid_amount_after_tax": 100000,
  "paid_from": "Débiteurs - TH",
  "paid_from_account_balance": 0,
  "paid_from_account_currency": "DA",
  "paid_from_account_type": "",
  "paid_to": "Espèces - TH",
  "paid_to_account_balance": 0,
  "paid_to_account_currency": "DA",
  "paid_to_account_type": "Cash",
  "party": "ABD ALLAH TORKI",
  "party_balance": 930160,
  "party_bank_account": null,
  "party_name": "ABD ALLAH TORKI",
  "party_type": "Customer",
  "payment_order": null,
  "payment_order_status": "Initiated",
  "payment_type": "Receive",
  "posting_date": "2024-10-24",
  "print_heading": null,
  "project": null,
  "purchase_taxes_and_charges_template": null,
  "received_amount": 100000,
  "received_amount_after_tax": 100000,
  "reference_date": "2024-10-24",
  "reference_no": null,
  "remarks": "Montant DA 100000 Reçu de ABD ALLAH TORKIMontant DA 100000 contre Sales Order 00014/2024.",
  "sales_taxes_and_charges_template": null,
  "source_exchange_rate": 1,
  "status": "Submitted",
  "target_exchange_rate": 1,
  "tax_withholding_category": null,
  "title": "ABD ALLAH TORKI",
  "total_allocated_amount": 100000,
  "total_taxes_and_charges": 0,
  "unallocated_amount": 0
}