{
  "allow_alternative_item": 0,
  "allow_negative_stock": 0,
  "asset_category": null,
  "asset_naming_series": null,
  "auto_create_assets": 0,
  "batch_number_series": null,
  "brand": null,
  "country_of_origin": null,
  "create_new_batch": 0,
  "creation": "2024-12-20 08:27:04.424502",
  "custom_invoicing_unit_price": 0,
  "custom_not_in_stock": 0,
  "custom_number_of_cartons": 0,
  "custom_packaging_type": "Per unit",
  "custom_parent_group_code": "Tous les Groupes d'Articles",
  "custom_quantity__carton": 0,
  "custom_retail_unit_selling_price": 0,
  "custom_special_unit_selling_price": 0,
  "custom_stock_alert": 0,
  "custom_unit_purchase_price": 0,
  "custom_unit_selling_price_in_semi_wholesale": 0,
  "custom_volume": 0,
  "custom_wholesale_unit_selling_price": 0,
  "customer": null,
  "customer_code": "",
  "customs_tariff_number": null,
  "default_bom": null,
  "default_item_manufacturer": null,
  "default_manufacturer_part_no": null,
  "default_material_request_type": "Purchase",
  "delivered_by_supplier": 0,
  "description": "description ",
  "disabled": 0,
  "docstatus": 0,
  "enable_deferred_expense": 0,
  "enable_deferred_revenue": 0,
  "end_of_life": "2099-12-31",
  "grant_commission": 1,
  "has_batch_no": 0,
  "has_expiry_date": 0,
  "has_serial_no": 0,
  "has_variants": 0,
  "idx": 6,
  "image": null,
  "include_item_in_manufacturing": 1,
  "inspection_required_before_delivery": 0,
  "inspection_required_before_purchase": 0,
  "is_customer_provided_item": 0,
  "is_fixed_asset": 0,
  "is_grouped_asset": 0,
  "is_purchase_item": 1,
  "is_sales_item": 1,
  "is_stock_item": 1,
  "is_sub_contracted_item": 0,
  "item_code": "A-code",
  "item_group": "Matières Premières",
  "item_name": "a-code",
  "last_purchase_rate": 0,
  "lead_time_days": 0,
  "max_discount": 0,
  "min_order_qty": 0,
  "modified": "2024-12-20 08:27:04.424502",
  "modified_by": "Administrator",
  "name": "A-code",
  "naming_series": "STO-ITEM-.YYYY.-",
  "no_of_months": 0,
  "no_of_months_exp": 0,
  "opening_stock": 0,
  "over_billing_allowance": 0,
  "over_delivery_receipt_allowance": 0,
  "owner": "Administrator",
  "purchase_uom": null,
  "quality_inspection_template": null,
  "retain_sample": 0,
  "safety_stock": 0,
  "sales_uom": null,
  "sample_quantity": 0,
  "serial_no_series": null,
  "shelf_life_in_days": 0,
  "standard_rate": 0,
  "stock_uom": "Joule",
  "total_projected_qty": 0,
  "valuation_method": "",
  "valuation_rate": 0,
  "variant_based_on": "Item Attribute",
  "variant_of": null,
  "warranty_period": null,
  "weight_per_unit": 0,
  "weight_uom": null
}