var m ={
  "actual_qty": 0,
  "against_blanket_order": 0,
  "amount": 780,
  "base_amount": 780,
  "base_net_amount": 780,
  "base_net_rate": 78,
  "base_price_list_rate": 70,
  "base_rate": 78,
  "base_rate_with_margin": 0,
  "billed_amt": 0,
  "blanket_order_rate": 0,
  "company_total_stock": 0,
  "conversion_factor": 1,
  "creation": "2024-12-22 11:55:32.025329",
  "delivered_by_supplier": 0,
  "delivered_qty": 0,
  "delivery_date": "2024-12-25",
  "description": "item 2",
  "discount_amount": -8,
  "discount_percentage": 0,
  "docstatus": 1,
  "doctype": "Sales Order Item",
  "ensure_delivery_based_on_produced_serial_no": 0,
  "grant_commission": 1,
  "gross_profit": 780,
  "idx": 1,
  "image": "",
  "is_free_item": 0,
  "is_stock_item": 1,
  "item_code": "item 2",
  "item_group": "Raw Material",
  "item_name": "item 2",
  "item_tax_rate": "{}",
  "margin_rate_or_amount": 8,
  "margin_type": "Amount",
  "modified": "2024-12-22 17:24:25.656799",
  "modified_by": "haddadrafik258@gmail.com",
  "name": "tbet544kp6",
  "net_amount": 780,
  "net_rate": 78,
  "ordered_qty": 0,
  "owner": "haddadrafik258@gmail.com",
  "page_break": 0,
  "parent": "SAL-ORD-2024-00022",
  "parentfield": "items",
  "parenttype": "Sales Order",
  "picked_qty": 0,
  "planned_qty": 0,
  "price_list_rate": 70,
  "pricing_rules": "",
  "produced_qty": 0,
  "production_plan_qty": 0,
  "projected_qty": 0,
  "qty": 10,
  "rate": 78,
  "rate_with_margin": 0,
  "reserve_stock": 0,
  "returned_qty": 0,
  "stock_qty": 10,
  "stock_reserved_qty": 0,
  "stock_uom": "Nos",
  "stock_uom_rate": 78,
  "total_weight": 0,
  "transaction_date": "2024-12-22",
  "uom": "Nos",
  "valuation_rate": 0,
  "warehouse": "Stores - I",
  "weight_per_unit": 0,
  "work_order_qty": 0
}